/* Copyright (c) The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package net.sf.mmm.service.api;

import net.sf.mmm.util.lang.api.Datatype;
import net.sf.mmm.util.lang.api.concern.Security;

/**
 * This is the interface for a security token to prevent <em>cross site request forgery</em> (CSRF) and
 * potentially other attacks. Such token is to be generated on the server send to the client. The client will
 * store it and then send the token within the next request(s). The server will validate that the token
 * {@link Object#equals(Object) equals} to the one that has been generated by the server. Typically the token
 * is generated during the login process and is then send with every subsequent request. This is sufficient to
 * prevent XSRF attacks and has no other impact on the client application. However, for highest security it is
 * also possible to generate one-time tokens with every request that are only valid for the next request. The
 * latter approach may cause problems with navigation history (back- and forward-button, etc.).
 *
 * @author Joerg Hohwiller (hohwille at users.sourceforge.net)
 * @since 1.0.0
 */
public interface CsrfToken extends Datatype, Security {

  // nothing to add...

}
